### PR TITLE
Refactor/fix naming conventions

### LINKED ISSUE #49: Clean up code/ remove unnecessary lines

### PR DESCRIPTION
**Pull request by BlueJessen**
What does this PR do?
- Changes naming conventions in hydration, sleep, and scripts.js
- Refactors sleep functions to reduce code
- Uses more dynamic naming conventions
Where should your reviewer start?
-line 7 hydration.js, line 14 sleep.js & line 61 scripts.js
What (if any) features are you implementing?
- N/A
What (if anything) did you refactor?
-Reduced sleep functions by adding a type to the argument list, means that similar functions can be dynamic
-Changed naming conventions to be active verbs
-Corrected naming conventions in classes to be more general
Were there any issues that arose?
-N/A
Is there anything that you need from your teammate?
- For them to know that they are great! 
- Also if yall have ideas to refactor the for loops in my widgets in scripts let me know I was having a hard time doing that. 
Any other comments, questions, or concerns?
- N/A

closes #49 #47 #46

### CODE REVIEW

File: src/scripts.js [hunk 1]
```diff
@@ -120,8 +120,8 @@ function initialSetup() {
   sleepRepo = new Sleep(sleepData.sleepData);
   hydrationRepo = new Hydration(hydrationData.hydrationData);
   randomUser = getRandomUser(userRepo.userData);
-  userToDisplay(randomUser, userRepo);
-  sleepDisplay(randomUser, sleepRepo);
+  displayUserInfo(randomUser, userRepo);
```
Comment (davidhdaw) [inline src/scripts.js:123]: I love all these names.

File: src/Sleep.js [hunk 2]
```diff
@@ -11,49 +11,30 @@ class Sleep {
...
-    return Number(averageSleepQuality.toFixed(1));
-  };
-
-  findDaySleepHours(userID, date) {
-    return this.sleepData.find(userData => userID === userData.userID && date === userData.date).hoursSlept;
-  };
-
-  findDaySleepQuality(userID, date) {
-    return this.sleepData.find(userData => userID === userData.userID && date === userData.date).sleepQuality;
+  findDateData(userID, date, type) {
```
Comment (davidhdaw) [inline src/Sleep.js:22]: This does seem DRYer but we'll need to go back through and and do another round of rewrites on our test suites for this formatting.

**Review by davidhdaw — APPROVED** [review]
